/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumaks.docx.templates.gui;
import javax.swing.*;
import java.awt.*;


/**
 *
 * @author kotyo
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        JFrame frame = new JFrame();
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        templates.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        chooseTemplate = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        openMainPage = new javax.swing.JButton();
        rightPanel = new javax.swing.JLayeredPane();
        mainPage = new javax.swing.JPanel();
        mainPageText = new javax.swing.JTextArea();
        mainPageLogo = new javax.swing.JLabel();
        templates = new javax.swing.JTabbedPane();
        rentPanel = new javax.swing.JPanel();
        rentButton = new javax.swing.JButton();
        rentImage = new javax.swing.JLabel();
        salesPanel = new javax.swing.JPanel();
        salesButton = new javax.swing.JButton();
        salesImage = new javax.swing.JLabel();
        invoicePanel = new javax.swing.JPanel();
        invoiceImage = new javax.swing.JLabel();
        invoiceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(193, 200, 228));
        setIconImages(null);
        setName("mainPage"); // NOI18N
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(193, 200, 228));
        leftPanel.setPreferredSize(new java.awt.Dimension(300, 1080));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chooseTemplate.setBackground(new java.awt.Color(86, 128, 233));
        chooseTemplate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        chooseTemplate.setForeground(new java.awt.Color(255, 255, 255));
        chooseTemplate.setText("Выбрать шаблон");
        chooseTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTemplateActionPerformed(evt);
            }
        });
        leftPanel.add(chooseTemplate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 149, 300, 100));

        closeButton.setBackground(new java.awt.Color(86, 128, 233));
        closeButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("Закрыть приложение");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        leftPanel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 300, 100));

        openMainPage.setBackground(new java.awt.Color(86, 128, 233));
        openMainPage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        openMainPage.setForeground(new java.awt.Color(255, 255, 255));
        openMainPage.setText("Главная");
        openMainPage.setPreferredSize(new java.awt.Dimension(300, 60));
        openMainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMainPageActionPerformed(evt);
            }
        });
        leftPanel.add(openMainPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, -1, 100));

        getContentPane().add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 890));

        rightPanel.setBackground(new java.awt.Color(193, 200, 228));
        rightPanel.setForeground(new java.awt.Color(0, 0, 0));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPage.setBackground(new java.awt.Color(193, 200, 228));
        mainPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPageText.setBackground(new java.awt.Color(193, 200, 228));
        mainPageText.setColumns(20);
        mainPageText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainPageText.setForeground(new java.awt.Color(255, 255, 255));
        mainPageText.setRows(5);
        mainPageText.setText("                Устали от рутинного заполнения документов?\n\n                     DoxTemplate берет эту задачу на себя! \n       Автоматизируйте процесс, сосредоточьтесь на важном \n           и закройте вопрос с документами за пару кликов.");
        mainPageText.setBorder(null);
        mainPage.add(mainPageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        mainPageLogo.setBackground(new java.awt.Color(255, 255, 255));
        mainPageLogo.setFont(new java.awt.Font("Adwaita Sans", 0, 18)); // NOI18N
        mainPageLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainPageLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Пользователь\\Desktop\\АНАЛ\\java\\docx-templates\\src\\main\\java\\image\\logo_1.png")); // NOI18N
        mainPageLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mainPage.add(mainPageLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 1160, 170));

        rightPanel.add(mainPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1310, 920));

        templates.setBackground(new java.awt.Color(86, 128, 233));
        templates.setForeground(new java.awt.Color(255, 255, 255));
        templates.setPreferredSize(new java.awt.Dimension(1620, 1080));

        rentPanel.setBackground(new java.awt.Color(193, 200, 228));
        rentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rentButton.setBackground(new java.awt.Color(86, 128, 233));
        rentButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        rentButton.setForeground(new java.awt.Color(255, 255, 255));
        rentButton.setText("Сформировать");
        rentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButtonActionPerformed(evt);
            }
        });
        rentPanel.add(rentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 1290, 60));

        rentImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Пользователь\\Desktop\\АНАЛ\\java\\docx-templates\\src\\main\\java\\image\\rent.jpg")); // NOI18N
        rentPanel.add(rentImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1250, 663));

        templates.addTab("Договор аренды", rentPanel);

        salesPanel.setBackground(new java.awt.Color(193, 200, 228));
        salesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salesButton.setBackground(new java.awt.Color(86, 128, 233));
        salesButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        salesButton.setForeground(new java.awt.Color(255, 255, 255));
        salesButton.setText("Сформировать");
        salesPanel.add(salesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 1290, 60));

        salesImage.setBackground(new java.awt.Color(193, 200, 228));
        salesImage.setForeground(new java.awt.Color(193, 200, 228));
        salesImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salesImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Пользователь\\Desktop\\АНАЛ\\java\\docx-templates\\src\\main\\java\\image\\sales.jpg")); // NOI18N
        salesPanel.add(salesImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        templates.addTab("Договор купли-продажи", salesPanel);

        invoicePanel.setBackground(new java.awt.Color(193, 200, 228));
        invoicePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invoiceImage.setBackground(new java.awt.Color(193, 200, 0));
        invoiceImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invoiceImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Пользователь\\Desktop\\АНАЛ\\java\\docx-templates\\src\\main\\java\\image\\invoice.jpg")); // NOI18N
        invoicePanel.add(invoiceImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 619));

        invoiceButton.setBackground(new java.awt.Color(86, 128, 233));
        invoiceButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        invoiceButton.setForeground(new java.awt.Color(255, 255, 255));
        invoiceButton.setText("Сформировать");
        invoicePanel.add(invoiceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 1290, 60));

        templates.addTab("Договор купли-продажи", invoicePanel);

        rightPanel.add(templates, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 890));

        getContentPane().add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTemplateActionPerformed
        mainPageLogo.setVisible(false);
        mainPageText.setVisible(false);
        mainPage.setVisible(false);
        templates.setVisible(true);
    }//GEN-LAST:event_chooseTemplateActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed
    //Главная
    private void openMainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMainPageActionPerformed
        templates.setVisible(false);
        if(!mainPageLogo.isVisible()){
            mainPageLogo.setVisible(true);
            mainPageText.setVisible(true);
            mainPage.setVisible(true);
        }
    }//GEN-LAST:event_openMainPageActionPerformed

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseTemplate;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton invoiceButton;
    private javax.swing.JLabel invoiceImage;
    private javax.swing.JPanel invoicePanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPage;
    private javax.swing.JLabel mainPageLogo;
    private javax.swing.JTextArea mainPageText;
    private javax.swing.JButton openMainPage;
    private javax.swing.JButton rentButton;
    private javax.swing.JLabel rentImage;
    private javax.swing.JPanel rentPanel;
    private javax.swing.JLayeredPane rightPanel;
    private javax.swing.JButton salesButton;
    private javax.swing.JLabel salesImage;
    private javax.swing.JPanel salesPanel;
    private javax.swing.JTabbedPane templates;
    // End of variables declaration//GEN-END:variables
}
