/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rumaks.docx.templates.gui;

import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import rumaks.docx.templates.Invoice;

/**
 *
 * @author kotyo
 */
public class FillInvoice extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FillInvoice.class.getName());
    private Map<String, String> data;

    /**
     * Creates new form invoiceFille
     */
    public FillInvoice(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        data = new HashMap<>(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        number = new org.jdesktop.swingx.JXTextField();
        date = new org.jdesktop.swingx.JXTextField();
        generate = new javax.swing.JButton();
        Right = new javax.swing.JPanel();
        customerName = new org.jdesktop.swingx.JXTextField();
        customerAddress = new org.jdesktop.swingx.JXTextField();
        customerINN = new org.jdesktop.swingx.JXTextField();
        customerKPP = new org.jdesktop.swingx.JXTextField();
        Bottom = new javax.swing.JPanel();
        itemName1 = new org.jdesktop.swingx.JXTextField();
        itemUnit1 = new org.jdesktop.swingx.JXTextField();
        itemQuantity1 = new org.jdesktop.swingx.JXTextField();
        itemPrice1 = new org.jdesktop.swingx.JXTextField();
        Left = new javax.swing.JPanel();
        providerName = new org.jdesktop.swingx.JXTextField();
        providerAddress = new org.jdesktop.swingx.JXTextField();
        providerINN = new org.jdesktop.swingx.JXTextField();
        providerKPP = new org.jdesktop.swingx.JXTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Top.setBackground(new java.awt.Color(193, 200, 228));
        Top.setPreferredSize(new java.awt.Dimension(400, 450));
        Top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        number.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number.setPrompt("Номер счёта_фактуры");
        number.setPromptBackround(new java.awt.Color(64, 86, 161));
        number.setPromptForeground(new java.awt.Color(255, 255, 255));
        Top.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 606, 32));

        date.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.setPrompt("Дата счёта-фактуры (в формате \"дд.мм.гггг\")");
        date.setPromptBackround(new java.awt.Color(64, 86, 161));
        date.setPromptForeground(new java.awt.Color(255, 255, 255));
        Top.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, 606, 32));

        getContentPane().add(Top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 618, 76));

        generate.setBackground(new java.awt.Color(86, 128, 233));
        generate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        generate.setForeground(new java.awt.Color(255, 255, 255));
        generate.setText("Сформировать");
        generate.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        getContentPane().add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 404, 606, 50));

        Right.setBackground(new java.awt.Color(193, 200, 228));
        Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerName.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        customerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        customerName.setPrompt("Наименование покупателя");
        customerName.setPromptBackround(new java.awt.Color(64, 86, 161));
        customerName.setPromptForeground(new java.awt.Color(255, 255, 255));
        Right.add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 294, 32));

        customerAddress.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        customerAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        customerAddress.setPrompt("Адрес покупателя");
        customerAddress.setPromptBackround(new java.awt.Color(64, 86, 161));
        customerAddress.setPromptForeground(new java.awt.Color(255, 255, 255));
        Right.add(customerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, 294, 32));

        customerINN.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        customerINN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        customerINN.setPrompt("ИНН покупателя");
        customerINN.setPromptBackround(new java.awt.Color(64, 86, 161));
        customerINN.setPromptForeground(new java.awt.Color(255, 255, 255));
        Right.add(customerINN, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 294, 32));

        customerKPP.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        customerKPP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        customerKPP.setPrompt("КПП покупателя");
        customerKPP.setPromptBackround(new java.awt.Color(64, 86, 161));
        customerKPP.setPromptForeground(new java.awt.Color(255, 255, 255));
        Right.add(customerKPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, 294, 38));

        getContentPane().add(Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 82, -1, 164));

        Bottom.setBackground(new java.awt.Color(193, 200, 228));
        Bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemName1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        itemName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemName1.setPrompt("Наименование товара");
        itemName1.setPromptBackround(new java.awt.Color(64, 86, 161));
        itemName1.setPromptForeground(new java.awt.Color(255, 255, 255));
        Bottom.add(itemName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 606, 32));

        itemUnit1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        itemUnit1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemUnit1.setPrompt("Единица измерения");
        itemUnit1.setPromptBackround(new java.awt.Color(64, 86, 161));
        itemUnit1.setPromptForeground(new java.awt.Color(255, 255, 255));
        Bottom.add(itemUnit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 606, 32));

        itemQuantity1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        itemQuantity1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemQuantity1.setPrompt("Количество");
        itemQuantity1.setPromptBackround(new java.awt.Color(64, 86, 161));
        itemQuantity1.setPromptForeground(new java.awt.Color(255, 255, 255));
        Bottom.add(itemQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 606, 32));

        itemPrice1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        itemPrice1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemPrice1.setPrompt("Цена за единицу");
        itemPrice1.setPromptBackround(new java.awt.Color(64, 86, 161));
        itemPrice1.setPromptForeground(new java.awt.Color(255, 255, 255));
        Bottom.add(itemPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 114, 606, 32));

        getContentPane().add(Bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 252, 620, -1));

        Left.setBackground(new java.awt.Color(193, 200, 228));
        Left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        providerName.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        providerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        providerName.setPrompt("Наименование поставщика");
        providerName.setPromptBackround(new java.awt.Color(64, 86, 161));
        providerName.setPromptForeground(new java.awt.Color(255, 255, 255));
        Left.add(providerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 300, 32));

        providerAddress.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        providerAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        providerAddress.setPrompt("Адрес поставщика");
        providerAddress.setPromptBackround(new java.awt.Color(64, 86, 161));
        providerAddress.setPromptForeground(new java.awt.Color(255, 255, 255));
        Left.add(providerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, 300, 32));

        providerINN.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        providerINN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        providerINN.setPrompt("ИНН поставщика");
        providerINN.setPromptBackround(new java.awt.Color(64, 86, 161));
        providerINN.setPromptForeground(new java.awt.Color(255, 255, 255));
        Left.add(providerINN, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 300, 32));

        providerKPP.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        providerKPP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        providerKPP.setPrompt("КПП поставщика");
        providerKPP.setPromptBackround(new java.awt.Color(64, 86, 161));
        providerKPP.setPromptForeground(new java.awt.Color(255, 255, 255));
        Left.add(providerKPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, 300, 38));

        getContentPane().add(Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, -1, 164));

        jPanel1.setBackground(new java.awt.Color(193, 200, 228));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
       // Собираем данные из формы
        data.clear();
        // Основные реквизиты документа
        data.put("number", number.getText());
        data.put("date", date.getText());

        // Данные поставщика
        data.put("providerName", providerName.getText());
        data.put("providerAddress", providerAddress.getText());
        data.put("providerINN", providerINN.getText());
        data.put("providerKPP", providerKPP.getText());

        // Данные покупателя
        data.put("customerName", customerName.getText());
        data.put("customerAddress", customerAddress.getText());
        data.put("customerINN", customerINN.getText());
        data.put("customerKPP", customerKPP.getText());

        // Товарные позиции
        data.put("itemName1", itemName1.getText());
        data.put("itemUnit1", itemUnit1.getText());
        data.put("itemQuantity1", itemQuantity1.getText());
        data.put("itemPrice1", itemPrice1.getText());

        // Создаем диалог выбора файла
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Сохранить счёт-фактуру");

        // Устанавливаем фильтр для .docx файлов
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Документы Word (*.docx)", "docx");
        fileChooser.setFileFilter(filter);

        // Предлагаем имя файла по умолчанию
        String defaultFileName = "Счёт-фактура_" + number.getText() + "_от_" + date.getText() + ".docx";
        fileChooser.setSelectedFile(new File(defaultFileName));

        // Показываем диалог сохранения
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Добавляем расширение .docx, если его нет
            if (!filePath.toLowerCase().endsWith(".docx")) {
                filePath += ".docx";
                fileToSave = new File(filePath);
            }

            // Проверка на существование файла
            if (fileToSave.exists()) {
                int response = JOptionPane.showConfirmDialog(this,
                    "Файл уже существует. Перезаписать?",
                    "Подтверждение",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

                if (response != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            // Создаем и сохраняем документ
            Invoice invoice = new Invoice(data);
            try {
                invoice.generateContent();
                invoice.saveToFile(filePath);

                JOptionPane.showMessageDialog(this, 
                    "Счёт-фактура успешно сохранена!\n" + filePath, 
                    "Сохранение завершено", 
                    JOptionPane.INFORMATION_MESSAGE);
            } catch (HeadlessException | IOException ex) {
                JOptionPane.showMessageDialog(this, 
                    "Ошибка при сохранении файла:\n" + ex.getMessage(), 
                    "Ошибка", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FillInvoice dialog = new FillInvoice(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel Top;
    private org.jdesktop.swingx.JXTextField customerAddress;
    private org.jdesktop.swingx.JXTextField customerINN;
    private org.jdesktop.swingx.JXTextField customerKPP;
    private org.jdesktop.swingx.JXTextField customerName;
    private org.jdesktop.swingx.JXTextField date;
    private javax.swing.JButton generate;
    private org.jdesktop.swingx.JXTextField itemName1;
    private org.jdesktop.swingx.JXTextField itemPrice1;
    private org.jdesktop.swingx.JXTextField itemQuantity1;
    private org.jdesktop.swingx.JXTextField itemUnit1;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXTextField number;
    private org.jdesktop.swingx.JXTextField providerAddress;
    private org.jdesktop.swingx.JXTextField providerINN;
    private org.jdesktop.swingx.JXTextField providerKPP;
    private org.jdesktop.swingx.JXTextField providerName;
    // End of variables declaration//GEN-END:variables
}
