/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rumaks.docx.templates.gui;

import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import rumaks.docx.templates.RentalAgreement;

/**
 *
 * @author kotyo
 */
public class FillRent extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FillRent.class.getName());
    private Map<String, String> data;
    /**
     * Creates new form rentFille
     */
    public FillRent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        data = new HashMap<>(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fields = new javax.swing.JPanel();
        agreementNumber = new org.jdesktop.swingx.JXTextField();
        agreementDate = new org.jdesktop.swingx.JXTextField();
        city = new org.jdesktop.swingx.JXTextField();
        landlordFullName = new org.jdesktop.swingx.JXTextField();
        landlordShortName = new org.jdesktop.swingx.JXTextField();
        tenantFullName = new org.jdesktop.swingx.JXTextField();
        tenantShortName = new org.jdesktop.swingx.JXTextField();
        propertyDescription = new org.jdesktop.swingx.JXTextField();
        propertyAddress = new org.jdesktop.swingx.JXTextField();
        startDate = new org.jdesktop.swingx.JXTextField();
        endDate = new org.jdesktop.swingx.JXTextField();
        rentAmount = new org.jdesktop.swingx.JXTextField();
        rentAmountWords = new org.jdesktop.swingx.JXTextField();
        paymentDay = new org.jdesktop.swingx.JXTextField();
        generate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fields.setBackground(new java.awt.Color(193, 200, 228));
        Fields.setPreferredSize(new java.awt.Dimension(400, 450));
        Fields.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agreementNumber.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        agreementNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        agreementNumber.setPrompt("Номер договора");
        agreementNumber.setPromptBackround(new java.awt.Color(64, 86, 161));
        agreementNumber.setPromptForeground(new java.awt.Color(255, 255, 255));
        Fields.add(agreementNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 388, 32));

        agreementDate.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        agreementDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        agreementDate.setPrompt("Дата заключения (в формате \"дд.мм.гггг\")");
        agreementDate.setPromptBackround(new java.awt.Color(64, 86, 161));
        agreementDate.setPromptForeground(new java.awt.Color(255, 255, 255));
        agreementDate.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(agreementDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, 388, 32));

        city.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        city.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        city.setPrompt("Город заключения");
        city.setPromptBackround(new java.awt.Color(64, 86, 161));
        city.setPromptForeground(new java.awt.Color(255, 255, 255));
        city.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 388, 32));

        landlordFullName.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        landlordFullName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        landlordFullName.setPrompt("Полное название компании арендодателя");
        landlordFullName.setPromptBackround(new java.awt.Color(64, 86, 161));
        landlordFullName.setPromptForeground(new java.awt.Color(255, 255, 255));
        landlordFullName.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(landlordFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, 388, 32));

        landlordShortName.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        landlordShortName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        landlordShortName.setPrompt("Краткое имя арендодателя");
        landlordShortName.setPromptBackround(new java.awt.Color(64, 86, 161));
        landlordShortName.setPromptForeground(new java.awt.Color(255, 255, 255));
        landlordShortName.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(landlordShortName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 158, 388, 32));

        tenantFullName.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        tenantFullName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tenantFullName.setPrompt("Полное название компании арендатора");
        tenantFullName.setPromptBackround(new java.awt.Color(64, 86, 161));
        tenantFullName.setPromptForeground(new java.awt.Color(255, 255, 255));
        tenantFullName.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(tenantFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 196, 388, 32));

        tenantShortName.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        tenantShortName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tenantShortName.setPrompt("Краткое имя арендатора");
        tenantShortName.setPromptBackround(new java.awt.Color(64, 86, 161));
        tenantShortName.setPromptForeground(new java.awt.Color(255, 255, 255));
        tenantShortName.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(tenantShortName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 234, 388, 32));

        propertyDescription.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        propertyDescription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertyDescription.setPrompt("Описание имущества");
        propertyDescription.setPromptBackround(new java.awt.Color(64, 86, 161));
        propertyDescription.setPromptForeground(new java.awt.Color(255, 255, 255));
        propertyDescription.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(propertyDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 272, 388, 32));

        propertyAddress.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        propertyAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertyAddress.setPrompt("Адрес имущества");
        propertyAddress.setPromptBackround(new java.awt.Color(64, 86, 161));
        propertyAddress.setPromptForeground(new java.awt.Color(255, 255, 255));
        propertyAddress.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(propertyAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 310, 388, 32));

        startDate.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        startDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        startDate.setPrompt("Дата начала аренды (в формате \"дд.мм.гггг\")");
        startDate.setPromptBackround(new java.awt.Color(64, 86, 161));
        startDate.setPromptForeground(new java.awt.Color(255, 255, 255));
        startDate.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 348, 388, 32));

        endDate.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        endDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        endDate.setPrompt("Дата окончания аренды (в формате \"дд.мм.гггг\")");
        endDate.setPromptBackround(new java.awt.Color(64, 86, 161));
        endDate.setPromptForeground(new java.awt.Color(255, 255, 255));
        endDate.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 386, 388, 32));

        rentAmount.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        rentAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rentAmount.setPrompt("Сумма арендной платы (цифрами)");
        rentAmount.setPromptBackround(new java.awt.Color(64, 86, 161));
        rentAmount.setPromptForeground(new java.awt.Color(255, 255, 255));
        rentAmount.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(rentAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 424, 388, 32));

        rentAmountWords.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        rentAmountWords.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rentAmountWords.setPrompt("Сумма арендной платы (словами)");
        rentAmountWords.setPromptBackround(new java.awt.Color(64, 86, 161));
        rentAmountWords.setPromptForeground(new java.awt.Color(255, 255, 255));
        rentAmountWords.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(rentAmountWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 462, 388, 32));

        paymentDay.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        paymentDay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paymentDay.setPrompt("Число месяца, до которого производится оплата");
        paymentDay.setPromptBackround(new java.awt.Color(64, 86, 161));
        paymentDay.setPromptForeground(new java.awt.Color(255, 255, 255));
        paymentDay.setSelectionColor(new java.awt.Color(64, 86, 161));
        Fields.add(paymentDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 500, 388, 32));

        getContentPane().add(Fields, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 538));

        generate.setBackground(new java.awt.Color(86, 128, 233));
        generate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        generate.setForeground(new java.awt.Color(255, 255, 255));
        generate.setText("Сформировать");
        generate.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        getContentPane().add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 544, 388, 50));

        jPanel1.setBackground(new java.awt.Color(193, 200, 228));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        data.clear();
        data.put("agreementNumber", agreementNumber.getText());
        data.put("agreementDate", agreementDate.getText());
        data.put("city", city.getText());
        data.put("landlordFullName", landlordFullName.getText());
        data.put("landlordShortName", landlordShortName.getText());
        data.put("tenantFullName", tenantFullName.getText());
        data.put("tenantShortName", tenantShortName.getText());
        data.put("propertyDescription", propertyDescription.getText());
        data.put("propertyAddress", propertyAddress.getText());
        data.put("startDate", startDate.getText());
        data.put("endDate", endDate.getText());
        data.put("rentAmount", rentAmount.getText());
        data.put("rentAmountWords", rentAmountWords.getText());
        data.put("paymentDay", paymentDay.getText());

        // Создаем диалог выбора файла
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Сохранить договор аренды");

        // Устанавливаем фильтр для .docx файлов
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Документы Word (*.docx)", "docx");
        fileChooser.setFileFilter(filter);

        // Предлагаем имя файла по умолчанию
        String defaultFileName = "Договор_аренды_" + agreementNumber.getText() + ".docx";
        fileChooser.setSelectedFile(new File(defaultFileName));

        // Показываем диалог сохранения
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Добавляем расширение .docx, если его нет
            if (!filePath.toLowerCase().endsWith(".docx")) {
                filePath += ".docx";
            }

            // Проверка на существование файла
            if (fileToSave.exists()) {
                int response = JOptionPane.showConfirmDialog(this,
                    "Файл уже существует. Перезаписать?",
                    "Подтверждение",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

                if (response != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            // Создаем и сохраняем документ
            RentalAgreement rent = new RentalAgreement(data);
            try {
                rent.generateContent();
                rent.saveToFile(filePath);

                JOptionPane.showMessageDialog(this, 
                    "Договор успешно сохранен!\n" + filePath, 
                    "Сохранение завершено", 
                    JOptionPane.INFORMATION_MESSAGE);
            } catch (HeadlessException | IOException ex) {
                JOptionPane.showMessageDialog(this, 
                    "Ошибка при сохранении файла:\n" + ex.getMessage(), 
                    "Ошибка", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FillRent dialog = new FillRent(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fields;
    private org.jdesktop.swingx.JXTextField agreementDate;
    private org.jdesktop.swingx.JXTextField agreementNumber;
    private org.jdesktop.swingx.JXTextField city;
    private org.jdesktop.swingx.JXTextField endDate;
    private javax.swing.JButton generate;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXTextField landlordFullName;
    private org.jdesktop.swingx.JXTextField landlordShortName;
    private org.jdesktop.swingx.JXTextField paymentDay;
    private org.jdesktop.swingx.JXTextField propertyAddress;
    private org.jdesktop.swingx.JXTextField propertyDescription;
    private org.jdesktop.swingx.JXTextField rentAmount;
    private org.jdesktop.swingx.JXTextField rentAmountWords;
    private org.jdesktop.swingx.JXTextField startDate;
    private org.jdesktop.swingx.JXTextField tenantFullName;
    private org.jdesktop.swingx.JXTextField tenantShortName;
    // End of variables declaration//GEN-END:variables
}
