/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rumaks.docx.templates.gui;

import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import rumaks.docx.templates.SalesContract;

/**
 *
 * @author kotyo
 */
public class FillSales extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FillSales.class.getName());
    private Map<String, String> data;

    /**
     * Creates new form salesContractFille
     * @param parent
     * @param modal
     */
    public FillSales(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        data = new HashMap<>();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left = new javax.swing.JPanel();
        sellerFullName = new javax.swing.JTextField();
        sellerSignatory = new javax.swing.JTextField();
        sellerAddress = new javax.swing.JTextField();
        sellerINN = new javax.swing.JTextField();
        sellerAccount = new javax.swing.JTextField();
        sellerBank = new javax.swing.JTextField();
        sellerBIK = new javax.swing.JTextField();
        bottom = new javax.swing.JPanel();
        productDescription = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        unit = new javax.swing.JTextField();
        totalPrice = new javax.swing.JTextField();
        totalPriceWords = new javax.swing.JTextField();
        paymentTerms = new javax.swing.JTextField();
        generate = new javax.swing.JButton();
        right = new javax.swing.JPanel();
        buyerFullName = new javax.swing.JTextField();
        buyerSignatory = new javax.swing.JTextField();
        buyerAddress = new javax.swing.JTextField();
        buyerINN = new javax.swing.JTextField();
        buyerAccount = new javax.swing.JTextField();
        buyerBank = new javax.swing.JTextField();
        buyerBIK = new javax.swing.JTextField();
        top = new javax.swing.JPanel();
        contractNumber = new javax.swing.JTextField();
        contractDate = new javax.swing.JTextField();
        city = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        left.setPreferredSize(new java.awt.Dimension(350, 266));

        sellerFullName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sellerFullName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerFullName.setText("Полное имя продавца");
        sellerFullName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sellerSignatory.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sellerSignatory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerSignatory.setText("ФИО подписанта продавца");
        sellerSignatory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sellerAddress.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sellerAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerAddress.setText(" Адрес продавца");
        sellerAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sellerINN.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sellerINN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerINN.setText("ИНН продавца");
        sellerINN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sellerAccount.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sellerAccount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerAccount.setText("Расчётный счёт продавца");
        sellerAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sellerBank.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sellerBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerBank.setText("Банк продавца");
        sellerBank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sellerBIK.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sellerBIK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerBIK.setText("БИК банка продавца");
        sellerBIK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sellerFullName)
                    .addComponent(sellerSignatory, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(sellerAddress)
                    .addComponent(sellerINN)
                    .addComponent(sellerAccount)
                    .addComponent(sellerBank)
                    .addComponent(sellerBIK))
                .addContainerGap())
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sellerFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellerSignatory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellerINN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellerBank, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellerBIK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        productDescription.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        productDescription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        productDescription.setText("Описание товара");

        quantity.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantity.setText("Количество товара");

        unit.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        unit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        unit.setText(" Единица измерения (например, \"шт.\")");

        totalPrice.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        totalPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPrice.setText("Общая стоимость (цифрами)");

        totalPriceWords.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        totalPriceWords.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPriceWords.setText("Общая стоимость (прописью)");

        paymentTerms.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        paymentTerms.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paymentTerms.setText("Условия оплаты");

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(productDescription)
                    .addComponent(quantity)
                    .addComponent(unit, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addComponent(totalPrice)
                    .addComponent(totalPriceWords)
                    .addComponent(paymentTerms))
                .addContainerGap())
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addComponent(productDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPriceWords, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentTerms, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        generate.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        generate.setText("Сформировать");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        right.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        right.setPreferredSize(new java.awt.Dimension(350, 266));

        buyerFullName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        buyerFullName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerFullName.setText("Полное имя покупателя");
        buyerFullName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buyerSignatory.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        buyerSignatory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerSignatory.setText("ФИО подписанта покупателя");
        buyerSignatory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buyerAddress.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        buyerAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerAddress.setText(" Адрес покупателя");
        buyerAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buyerINN.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        buyerINN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerINN.setText("ИНН покупателя");
        buyerINN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buyerAccount.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        buyerAccount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerAccount.setText("Расчётный счёт покупателя");
        buyerAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buyerBank.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        buyerBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerBank.setText("Банк покупателя");
        buyerBank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buyerBIK.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        buyerBIK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerBIK.setText("БИК банка покупателя");
        buyerBIK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buyerSignatory, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(buyerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(buyerINN, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(buyerAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(buyerBank, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(buyerBIK, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(buyerFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                .addContainerGap())
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buyerFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyerSignatory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyerINN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyerBank, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyerBIK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contractNumber.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        contractNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contractNumber.setText("Номер договора");

        contractDate.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        contractDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contractDate.setText("Дата заключения (в формате \"дд.мм.гггг\")");

        city.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        city.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        city.setText("Город заключения");

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(city)
                    .addComponent(contractDate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contractNumber))
                .addContainerGap())
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contractNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contractDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(top, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(right, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
         // Собираем данные из формы
        data.clear();
        data.put("contractNumber", contractNumber.getText());
        data.put("contractDate", contractDate.getText());
        data.put("city", city.getText());
        data.put("sellerFullName", sellerFullName.getText());
        data.put("sellerSignatory", sellerSignatory.getText());
        data.put("sellerAddress", sellerAddress.getText());
        data.put("sellerINN", sellerINN.getText());
        data.put("sellerAccount", sellerAccount.getText());
        data.put("sellerBank", sellerBank.getText());
        data.put("sellerBIK", sellerBIK.getText());
        data.put("buyerFullName", buyerFullName.getText());
        data.put("buyerSignatory", buyerSignatory.getText());
        data.put("buyerAddress", buyerAddress.getText());
        data.put("buyerINN", buyerINN.getText());
        data.put("buyerAccount", buyerAccount.getText());
        data.put("buyerBank", buyerBank.getText());
        data.put("buyerBIK", buyerBIK.getText());
        data.put("productDescription", productDescription.getText());
        data.put("quantity", quantity.getText());
        data.put("unit", unit.getText());
        data.put("totalPrice", totalPrice.getText());
        data.put("totalPriceWords", totalPriceWords.getText());
        data.put("paymentTerms", paymentTerms.getText());

        // Создаем диалог выбора файла
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Сохранить договор купли-продажи");

        // Устанавливаем фильтр для .docx файлов
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Документы Word (*.docx)", "docx");
        fileChooser.setFileFilter(filter);

        // Предлагаем имя файла по умолчанию
        String defaultFileName = "Договор_КП_" + contractNumber.getText() + ".docx";
        fileChooser.setSelectedFile(new File(defaultFileName));

        // Показываем диалог сохранения
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Добавляем расширение .docx, если его нет
            if (!filePath.toLowerCase().endsWith(".docx")) {
                filePath += ".docx";
                fileToSave = new File(filePath);
            }

            // Проверка на существование файла
            if (fileToSave.exists()) {
                int response = JOptionPane.showConfirmDialog(this,
                    "Файл уже существует. Перезаписать?",
                    "Подтверждение",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

                if (response != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            // Создаем и сохраняем документ
            SalesContract sales = new SalesContract(data);
            try {
                sales.generateContent();
                sales.saveToFile(filePath);

                JOptionPane.showMessageDialog(this, 
                    "Договор успешно сохранен!\n" + filePath, 
                    "Сохранение завершено", 
                    JOptionPane.INFORMATION_MESSAGE);
            } catch (HeadlessException | IOException ex) {
                JOptionPane.showMessageDialog(this, 
                    "Ошибка при сохранении файла:\n" + ex.getMessage(), 
                    "Ошибка", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FillSales dialog = new FillSales(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottom;
    private javax.swing.JTextField buyerAccount;
    private javax.swing.JTextField buyerAddress;
    private javax.swing.JTextField buyerBIK;
    private javax.swing.JTextField buyerBank;
    private javax.swing.JTextField buyerFullName;
    private javax.swing.JTextField buyerINN;
    private javax.swing.JTextField buyerSignatory;
    private javax.swing.JTextField city;
    private javax.swing.JTextField contractDate;
    private javax.swing.JTextField contractNumber;
    private javax.swing.JButton generate;
    private javax.swing.JPanel left;
    private javax.swing.JTextField paymentTerms;
    private javax.swing.JTextField productDescription;
    private javax.swing.JTextField quantity;
    private javax.swing.JPanel right;
    private javax.swing.JTextField sellerAccount;
    private javax.swing.JTextField sellerAddress;
    private javax.swing.JTextField sellerBIK;
    private javax.swing.JTextField sellerBank;
    private javax.swing.JTextField sellerFullName;
    private javax.swing.JTextField sellerINN;
    private javax.swing.JTextField sellerSignatory;
    private javax.swing.JPanel top;
    private javax.swing.JTextField totalPrice;
    private javax.swing.JTextField totalPriceWords;
    private javax.swing.JTextField unit;
    // End of variables declaration//GEN-END:variables
}
