/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rumaks.docx.templates.gui;

import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import rumaks.docx.templates.SalesContract;

/**
 *
 * @author kotyo
 */
public class FillSales extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FillSales.class.getName());
    private Map<String, String> data;

    /**
     * Creates new form salesContractFille
     * @param parent
     * @param modal
     */
    public FillSales(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        data = new HashMap<>();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left = new javax.swing.JPanel();
        sellerFullName = new org.jdesktop.swingx.JXTextField();
        sellerSignatory = new org.jdesktop.swingx.JXTextField();
        sellerAddress = new org.jdesktop.swingx.JXTextField();
        sellerINN = new org.jdesktop.swingx.JXTextField();
        sellerAccount = new org.jdesktop.swingx.JXTextField();
        sellerBank = new org.jdesktop.swingx.JXTextField();
        sellerBIK = new org.jdesktop.swingx.JXTextField();
        bottom = new javax.swing.JPanel();
        productDescription = new org.jdesktop.swingx.JXTextField();
        quantity = new org.jdesktop.swingx.JXTextField();
        unit = new org.jdesktop.swingx.JXTextField();
        totalPrice = new org.jdesktop.swingx.JXTextField();
        totalPriceWords = new org.jdesktop.swingx.JXTextField();
        paymentTerms = new org.jdesktop.swingx.JXTextField();
        generate = new javax.swing.JButton();
        right = new javax.swing.JPanel();
        buyerFullName = new org.jdesktop.swingx.JXTextField();
        buyerSignatory = new org.jdesktop.swingx.JXTextField();
        buyerAddress = new org.jdesktop.swingx.JXTextField();
        buyerINN = new org.jdesktop.swingx.JXTextField();
        buyerAccount = new org.jdesktop.swingx.JXTextField();
        buyerBank = new org.jdesktop.swingx.JXTextField();
        buyerBIK = new org.jdesktop.swingx.JXTextField();
        top = new javax.swing.JPanel();
        contractNumber = new org.jdesktop.swingx.JXTextField();
        contractDate = new org.jdesktop.swingx.JXTextField();
        city = new org.jdesktop.swingx.JXTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(193, 200, 228));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(193, 200, 228));
        left.setPreferredSize(new java.awt.Dimension(350, 266));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sellerFullName.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        sellerFullName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerFullName.setPrompt("Полное имя продавца");
        sellerFullName.setPromptBackround(new java.awt.Color(64, 86, 161));
        sellerFullName.setPromptForeground(new java.awt.Color(255, 255, 255));
        left.add(sellerFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 338, 32));

        sellerSignatory.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        sellerSignatory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerSignatory.setPrompt("ФИО подписанта продавца");
        sellerSignatory.setPromptBackround(new java.awt.Color(64, 86, 161));
        sellerSignatory.setPromptForeground(new java.awt.Color(255, 255, 255));
        left.add(sellerSignatory, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, 338, 32));

        sellerAddress.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        sellerAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerAddress.setPrompt("Адрес продавца");
        sellerAddress.setPromptBackround(new java.awt.Color(64, 86, 161));
        sellerAddress.setPromptForeground(new java.awt.Color(255, 255, 255));
        left.add(sellerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 338, 32));

        sellerINN.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        sellerINN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerINN.setPrompt("ИНН продавца");
        sellerINN.setPromptBackround(new java.awt.Color(64, 86, 161));
        sellerINN.setPromptForeground(new java.awt.Color(255, 255, 255));
        left.add(sellerINN, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, 338, 32));

        sellerAccount.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        sellerAccount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerAccount.setPrompt("Расчётный счёт продавца");
        sellerAccount.setPromptBackround(new java.awt.Color(64, 86, 161));
        sellerAccount.setPromptForeground(new java.awt.Color(255, 255, 255));
        left.add(sellerAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 158, 338, 32));

        sellerBank.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        sellerBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerBank.setPrompt("Банк продавца");
        sellerBank.setPromptBackround(new java.awt.Color(64, 86, 161));
        sellerBank.setPromptForeground(new java.awt.Color(255, 255, 255));
        left.add(sellerBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 196, 338, 32));

        sellerBIK.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        sellerBIK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sellerBIK.setPrompt("БИК банка продавца");
        sellerBIK.setPromptBackround(new java.awt.Color(64, 86, 161));
        sellerBIK.setPromptForeground(new java.awt.Color(255, 255, 255));
        sellerBIK.setSelectedTextColor(new java.awt.Color(64, 86, 161));
        left.add(sellerBIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 234, 338, 32));

        getContentPane().add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, -1, -1));

        bottom.setBackground(new java.awt.Color(193, 200, 228));
        bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productDescription.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        productDescription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        productDescription.setPrompt("Описание товара");
        productDescription.setPromptBackround(new java.awt.Color(64, 86, 161));
        productDescription.setPromptForeground(new java.awt.Color(255, 255, 255));
        bottom.add(productDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 688, 32));

        quantity.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantity.setPrompt("Количество товара");
        quantity.setPromptBackround(new java.awt.Color(64, 86, 161));
        quantity.setPromptForeground(new java.awt.Color(255, 255, 255));
        bottom.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, 688, 34));

        unit.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        unit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        unit.setPrompt("Единица измерения (например, \"шт.\")");
        unit.setPromptBackround(new java.awt.Color(64, 86, 161));
        unit.setPromptForeground(new java.awt.Color(255, 255, 255));
        bottom.add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 688, 32));

        totalPrice.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        totalPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPrice.setPrompt("Общая стоимость (цифрами)");
        totalPrice.setPromptBackround(new java.awt.Color(64, 86, 161));
        totalPrice.setPromptForeground(new java.awt.Color(255, 255, 255));
        bottom.add(totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 114, 688, 32));

        totalPriceWords.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        totalPriceWords.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPriceWords.setPrompt("Общая стоимость (прописью)");
        totalPriceWords.setPromptBackround(new java.awt.Color(64, 86, 161));
        totalPriceWords.setPromptForeground(new java.awt.Color(255, 255, 255));
        bottom.add(totalPriceWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 152, 688, 32));

        paymentTerms.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        paymentTerms.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paymentTerms.setPrompt("Условия оплаты");
        paymentTerms.setPromptBackround(new java.awt.Color(64, 86, 161));
        paymentTerms.setPromptForeground(new java.awt.Color(255, 255, 255));
        bottom.add(paymentTerms, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 190, 688, 37));

        getContentPane().add(bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 700, -1));

        generate.setBackground(new java.awt.Color(86, 128, 233));
        generate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        generate.setForeground(new java.awt.Color(255, 255, 255));
        generate.setText("Сформировать");
        generate.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        getContentPane().add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 645, 688, 64));

        right.setBackground(new java.awt.Color(193, 200, 228));
        right.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        right.setPreferredSize(new java.awt.Dimension(350, 266));

        buyerFullName.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        buyerFullName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerFullName.setPrompt("Полное имя покупателя");
        buyerFullName.setPromptBackround(new java.awt.Color(64, 86, 161));
        buyerFullName.setPromptForeground(new java.awt.Color(255, 255, 255));

        buyerSignatory.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        buyerSignatory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerSignatory.setPrompt("ФИО подписанта покупателя");
        buyerSignatory.setPromptBackround(new java.awt.Color(64, 86, 161));
        buyerSignatory.setPromptForeground(new java.awt.Color(255, 255, 255));

        buyerAddress.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        buyerAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerAddress.setPrompt("Адрес покупателя");
        buyerAddress.setPromptBackround(new java.awt.Color(64, 86, 161));
        buyerAddress.setPromptForeground(new java.awt.Color(255, 255, 255));

        buyerINN.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        buyerINN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerINN.setPrompt("ИНН покупателя");
        buyerINN.setPromptBackround(new java.awt.Color(64, 86, 161));
        buyerINN.setPromptForeground(new java.awt.Color(255, 255, 255));

        buyerAccount.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        buyerAccount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerAccount.setPrompt("Расчётный счёт покупателя");
        buyerAccount.setPromptBackround(new java.awt.Color(64, 86, 161));
        buyerAccount.setPromptForeground(new java.awt.Color(255, 255, 255));

        buyerBank.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        buyerBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerBank.setPrompt("Банк покупателя");
        buyerBank.setPromptBackround(new java.awt.Color(64, 86, 161));
        buyerBank.setPromptForeground(new java.awt.Color(255, 255, 255));

        buyerBIK.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        buyerBIK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buyerBIK.setPrompt("БИК банка покупателя");
        buyerBIK.setPromptBackround(new java.awt.Color(64, 86, 161));
        buyerBIK.setPromptForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buyerFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyerSignatory, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyerBank, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyerBIK, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buyerINN, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(buyerFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(buyerSignatory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(buyerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(buyerINN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(buyerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(buyerBank, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(buyerBIK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 128, 344, -1));

        top.setBackground(new java.awt.Color(193, 200, 228));
        top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contractNumber.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        contractNumber.setForeground(new java.awt.Color(255, 255, 255));
        contractNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contractNumber.setPrompt("Номер договора");
        contractNumber.setPromptBackround(new java.awt.Color(64, 86, 161));
        contractNumber.setPromptForeground(new java.awt.Color(255, 255, 255));
        top.add(contractNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 688, 32));

        contractDate.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        contractDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contractDate.setPrompt("Дата заключения (в формате \"дд.мм.гггг\")");
        contractDate.setPromptBackround(new java.awt.Color(64, 86, 161));
        contractDate.setPromptForeground(new java.awt.Color(255, 255, 255));
        top.add(contractDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, 688, 34));

        city.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        city.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        city.setPrompt("Город заключения");
        city.setPromptBackround(new java.awt.Color(64, 86, 161));
        city.setPromptForeground(new java.awt.Color(255, 255, 255));
        top.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 84, 688, 32));

        getContentPane().add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 700, -1));

        jPanel1.setBackground(new java.awt.Color(193, 200, 228));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
         // Собираем данные из формы
        data.clear();
        data.put("contractNumber", contractNumber.getText());
        data.put("contractDate", contractDate.getText());
        data.put("city", city.getText());
        data.put("sellerFullName", sellerFullName.getText());
        data.put("sellerSignatory", sellerSignatory.getText());
        data.put("sellerAddress", sellerAddress.getText());
        data.put("sellerINN", sellerINN.getText());
        data.put("sellerAccount", sellerAccount.getText());
        data.put("sellerBank", sellerBank.getText());
        data.put("sellerBIK", sellerBIK.getText());
        data.put("buyerFullName", buyerFullName.getText());
        data.put("buyerSignatory", buyerSignatory.getText());
        data.put("buyerAddress", buyerAddress.getText());
        data.put("buyerINN", buyerINN.getText());
        data.put("buyerAccount", buyerAccount.getText());
        data.put("buyerBank", buyerBank.getText());
        data.put("buyerBIK", buyerBIK.getText());
        data.put("productDescription", productDescription.getText());
        data.put("quantity", quantity.getText());
        data.put("unit", unit.getText());
        data.put("totalPrice", totalPrice.getText());
        data.put("totalPriceWords", totalPriceWords.getText());
        data.put("paymentTerms", paymentTerms.getText());

        // Создаем диалог выбора файла
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Сохранить договор купли-продажи");

        // Устанавливаем фильтр для .docx файлов
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Документы Word (*.docx)", "docx");
        fileChooser.setFileFilter(filter);

        // Предлагаем имя файла по умолчанию
        String defaultFileName = "Договор_КП_" + contractNumber.getText() + ".docx";
        fileChooser.setSelectedFile(new File(defaultFileName));

        // Показываем диалог сохранения
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Добавляем расширение .docx, если его нет
            if (!filePath.toLowerCase().endsWith(".docx")) {
                filePath += ".docx";
                fileToSave = new File(filePath);
            }

            // Проверка на существование файла
            if (fileToSave.exists()) {
                int response = JOptionPane.showConfirmDialog(this,
                    "Файл уже существует. Перезаписать?",
                    "Подтверждение",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

                if (response != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            // Создаем и сохраняем документ
            SalesContract sales = new SalesContract(data);
            try {
                sales.generateContent();
                sales.saveToFile(filePath);

                JOptionPane.showMessageDialog(this, 
                    "Договор успешно сохранен!\n" + filePath, 
                    "Сохранение завершено", 
                    JOptionPane.INFORMATION_MESSAGE);
            } catch (HeadlessException | IOException ex) {
                JOptionPane.showMessageDialog(this, 
                    "Ошибка при сохранении файла:\n" + ex.getMessage(), 
                    "Ошибка", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FillSales dialog = new FillSales(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottom;
    private org.jdesktop.swingx.JXTextField buyerAccount;
    private org.jdesktop.swingx.JXTextField buyerAddress;
    private org.jdesktop.swingx.JXTextField buyerBIK;
    private org.jdesktop.swingx.JXTextField buyerBank;
    private org.jdesktop.swingx.JXTextField buyerFullName;
    private org.jdesktop.swingx.JXTextField buyerINN;
    private org.jdesktop.swingx.JXTextField buyerSignatory;
    private org.jdesktop.swingx.JXTextField city;
    private org.jdesktop.swingx.JXTextField contractDate;
    private org.jdesktop.swingx.JXTextField contractNumber;
    private javax.swing.JButton generate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel left;
    private org.jdesktop.swingx.JXTextField paymentTerms;
    private org.jdesktop.swingx.JXTextField productDescription;
    private org.jdesktop.swingx.JXTextField quantity;
    private javax.swing.JPanel right;
    private org.jdesktop.swingx.JXTextField sellerAccount;
    private org.jdesktop.swingx.JXTextField sellerAddress;
    private org.jdesktop.swingx.JXTextField sellerBIK;
    private org.jdesktop.swingx.JXTextField sellerBank;
    private org.jdesktop.swingx.JXTextField sellerFullName;
    private org.jdesktop.swingx.JXTextField sellerINN;
    private org.jdesktop.swingx.JXTextField sellerSignatory;
    private javax.swing.JPanel top;
    private org.jdesktop.swingx.JXTextField totalPrice;
    private org.jdesktop.swingx.JXTextField totalPriceWords;
    private org.jdesktop.swingx.JXTextField unit;
    // End of variables declaration//GEN-END:variables
}
