/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumaks.docx.templates.gui;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author kotyo
 */
public class invoiceFiller extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(invoiceFiller.class.getName());

    /**
     * Creates new form invoiceFiller
     */
    public invoiceFiller() {
        initComponents();
        Map<String, String> data = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        number = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        generate = new javax.swing.JButton();
        Right = new javax.swing.JPanel();
        customerName = new javax.swing.JTextField();
        customerAddress = new javax.swing.JTextField();
        customerINN = new javax.swing.JTextField();
        customerKPP = new javax.swing.JTextField();
        Left = new javax.swing.JPanel();
        providerName = new javax.swing.JTextField();
        providerAddress = new javax.swing.JTextField();
        providerINN = new javax.swing.JTextField();
        providerKPP = new javax.swing.JTextField();
        Bottom = new javax.swing.JPanel();
        itemName1 = new javax.swing.JTextField();
        itemUnit1 = new javax.swing.JTextField();
        itemPrice1 = new javax.swing.JTextField();
        itemQuantity1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setSize(getPreferredSize());

        Top.setPreferredSize(new java.awt.Dimension(400, 450));

        number.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number.setText("Номер счёта-фактуры");

        date.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.setText("Дата счёта-фактуры (в формате \"дд.мм.гггг\")");

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(number)
                    .addComponent(date))
                .addContainerGap())
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        generate.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        generate.setText("Сформировать");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        customerName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        customerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        customerName.setText("Наименование покупателя");

        customerAddress.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        customerAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        customerAddress.setText("Адрес покупателя");

        customerINN.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        customerINN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        customerINN.setText("ИНН покупателя");

        customerKPP.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        customerKPP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        customerKPP.setText("КПП покупателя");

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerKPP)
                    .addComponent(customerINN, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerName, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addContainerGap())
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerINN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerKPP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        providerName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        providerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        providerName.setText("Наименование поставщика");

        providerAddress.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        providerAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        providerAddress.setText("Адрес поставщика");
        providerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerAddressActionPerformed(evt);
            }
        });

        providerINN.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        providerINN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        providerINN.setText("ИНН поставщика");

        providerKPP.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        providerKPP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        providerKPP.setText("КПП поставщика");

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(providerName)
                    .addComponent(providerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(providerINN, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(providerKPP, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(providerName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(providerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(providerINN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(providerKPP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemName1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        itemName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemName1.setText("Наименование товара");

        itemUnit1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        itemUnit1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemUnit1.setText("Единица измерения");

        itemPrice1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        itemPrice1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemPrice1.setText("Цена за единицу");

        itemQuantity1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        itemQuantity1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemQuantity1.setText("Количество");

        javax.swing.GroupLayout BottomLayout = new javax.swing.GroupLayout(Bottom);
        Bottom.setLayout(BottomLayout);
        BottomLayout.setHorizontalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemName1)
            .addComponent(itemUnit1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(itemQuantity1)
            .addComponent(itemPrice1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        BottomLayout.setVerticalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomLayout.createSequentialGroup()
                .addComponent(itemName1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Top, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Top, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateActionPerformed

    private void providerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providerAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new invoiceFiller().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel Top;
    private javax.swing.JTextField customerAddress;
    private javax.swing.JTextField customerINN;
    private javax.swing.JTextField customerKPP;
    private javax.swing.JTextField customerName;
    private javax.swing.JTextField date;
    private javax.swing.JButton generate;
    private javax.swing.JTextField itemName1;
    private javax.swing.JTextField itemPrice1;
    private javax.swing.JTextField itemQuantity1;
    private javax.swing.JTextField itemUnit1;
    private javax.swing.JTextField number;
    private javax.swing.JTextField providerAddress;
    private javax.swing.JTextField providerINN;
    private javax.swing.JTextField providerKPP;
    private javax.swing.JTextField providerName;
    // End of variables declaration//GEN-END:variables
}
