/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumaks.docx.templates.gui;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author kotyo
 */
public class rentFiller extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(rentFiller.class.getName());

    /**
     * Creates new form invoiceFiller
     */
    public rentFiller() {
        initComponents();
        Map<String, String> data = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fields = new javax.swing.JPanel();
        agreementNumber = new javax.swing.JTextField();
        agreementDate = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        tenantFullName = new javax.swing.JTextField();
        landlordShortName = new javax.swing.JTextField();
        landlordFullName = new javax.swing.JTextField();
        startDate = new javax.swing.JTextField();
        rentAmount = new javax.swing.JTextField();
        endDate = new javax.swing.JTextField();
        propertyAddress = new javax.swing.JTextField();
        propertyDescription = new javax.swing.JTextField();
        tenantShortName = new javax.swing.JTextField();
        rentAmountWords = new javax.swing.JTextField();
        paymentDay = new javax.swing.JTextField();
        generate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setSize(getPreferredSize());

        Fields.setPreferredSize(new java.awt.Dimension(400, 450));

        agreementNumber.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        agreementNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        agreementNumber.setText("Номер договора");

        agreementDate.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        agreementDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        agreementDate.setText("Дата заключения (в формате \"дд.мм.гггг\")");

        city.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        city.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        city.setText("Город заключения");

        tenantFullName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tenantFullName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tenantFullName.setText("Полное название компании арендатора");

        landlordShortName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        landlordShortName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        landlordShortName.setText("Краткое имя арендодателя ");

        landlordFullName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        landlordFullName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        landlordFullName.setText("Полное название компании арендодателя");

        startDate.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        startDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        startDate.setText("Дата начала аренды (в формате \"дд.мм.гггг\")");

        rentAmount.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rentAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rentAmount.setText("Сумма арендной платы (цифрами)");

        endDate.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        endDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        endDate.setText("Дата окончания аренды (в формате \"дд.мм.гггг\")");

        propertyAddress.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        propertyAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertyAddress.setText("Адрес имущества");

        propertyDescription.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        propertyDescription.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertyDescription.setText("Описание имущества");

        tenantShortName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tenantShortName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tenantShortName.setText("Краткое имя арендатора");

        rentAmountWords.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        rentAmountWords.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rentAmountWords.setText("Сумма арендной платы (словами)");

        paymentDay.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        paymentDay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paymentDay.setText("Число месяца, до которого производится оплата");

        javax.swing.GroupLayout FieldsLayout = new javax.swing.GroupLayout(Fields);
        Fields.setLayout(FieldsLayout);
        FieldsLayout.setHorizontalGroup(
            FieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agreementNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agreementDate)
                    .addComponent(city)
                    .addComponent(tenantFullName)
                    .addComponent(landlordShortName)
                    .addComponent(startDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rentAmount)
                    .addComponent(endDate)
                    .addComponent(propertyAddress)
                    .addComponent(propertyDescription)
                    .addComponent(tenantShortName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rentAmountWords)
                    .addComponent(paymentDay)
                    .addComponent(landlordFullName))
                .addContainerGap())
        );
        FieldsLayout.setVerticalGroup(
            FieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agreementNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agreementDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordShortName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenantFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenantShortName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertyDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentAmountWords, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentDay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        generate.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        generate.setText("Сформировать");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fields, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generate, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fields, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new rentFiller().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fields;
    private javax.swing.JTextField agreementDate;
    private javax.swing.JTextField agreementNumber;
    private javax.swing.JTextField city;
    private javax.swing.JTextField endDate;
    private javax.swing.JButton generate;
    private javax.swing.JTextField landlordFullName;
    private javax.swing.JTextField landlordShortName;
    private javax.swing.JTextField paymentDay;
    private javax.swing.JTextField propertyAddress;
    private javax.swing.JTextField propertyDescription;
    private javax.swing.JTextField rentAmount;
    private javax.swing.JTextField rentAmountWords;
    private javax.swing.JTextField startDate;
    private javax.swing.JTextField tenantFullName;
    private javax.swing.JTextField tenantShortName;
    // End of variables declaration//GEN-END:variables
}
